"""
Pairwise Feature Extraction Engine for Candidate Entity Pairs.
Amazon ML Challenge 2026.

Extracts rich lexical, numerical, and structural similarity signals between S1 and Candidate Target.
Operates strictly on candidate pairs generated by Champion v2.
"""

import re
from typing import Dict, List, Set, Any
from blocking.normalization import (
    normalize_business_name,
    normalize_business_address,
    clean_domain_or_handle,
    collapse_double_consonants,
    extract_clean_digits,
    extract_consonant_trigram,
    extract_alphanumeric_units,
    extract_state_code
)
import jellyfish

def jaccard_similarity(set_a: Set[Any], set_b: Set[Any]) -> float:
    """Compute Jaccard similarity between two sets."""
    if not set_a and not set_b:
        return 1.0
    if not set_a or not set_b:
        return 0.0
    intersection = len(set_a & set_b)
    union = len(set_a | set_b)
    return intersection / union if union else 0.0

def levenshtein_similarity(s1: str, s2: str) -> float:
    """Compute normalized character Levenshtein similarity [0.0, 1.0]."""
    if s1 == s2:
        return 1.0
    if not s1 or not s2:
        return 0.0
    len1, len2 = len(s1), len(s2)
    # Optimized 1D DP array
    dp = list(range(len2 + 1))
    for i in range(1, len1 + 1):
        prev = dp[0]
        dp[0] = i
        c1 = s1[i - 1]
        for j in range(1, len2 + 1):
            temp = dp[j]
            cost = 0 if c1 == s2[j - 1] else 1
            dp[j] = min(dp[j] + 1, dp[j - 1] + 1, prev + cost)
            prev = temp
    dist = dp[len2]
    max_len = max(len1, len2)
    return 1.0 - (dist / max_len) if max_len > 0 else 0.0

def extract_pairwise_features(s1_feat: dict, target_feat: dict) -> Dict[str, float]:
    """
    Extract a dictionary of numerical features for a single candidate pair.
    """
    # 1. Name Features
    exact_core_match = 1.0 if (s1_feat['core'] and s1_feat['core'] == target_feat['core']) else 0.0
    token_jaccard = jaccard_similarity(set(s1_feat['tokens']), set(target_feat['tokens']))
    ngram_jaccard = jaccard_similarity(set(s1_feat.get('ngrams', [])), set(target_feat.get('ngrams', [])))
    lev_name = levenshtein_similarity(s1_feat['core'], target_feat['core'])
    prefix4_match = 1.0 if (s1_feat['prefix4'] and s1_feat['prefix4'] == target_feat['prefix4']) else 0.0
    cons_tri_match = 1.0 if (s1_feat['consonant_tri'] and s1_feat['consonant_tri'] == target_feat['consonant_tri']) else 0.0
    
    collapsed_match = 1.0 if (s1_feat['core_collapsed'] and s1_feat['core_collapsed'] == target_feat['core_collapsed']) else 0.0

    # Domain / Handle similarity
    domain_match = 0.0
    if s1_feat['domain_stem'] and target_feat['domain_stem']:
        domain_match = 1.0 if s1_feat['domain_stem'] == target_feat['domain_stem'] else 0.0
    elif s1_feat['domain_stem'] and s1_feat['domain_stem'] == target_feat['nospace_core']:
        domain_match = 1.0
    elif target_feat['domain_stem'] and target_feat['domain_stem'] == s1_feat['nospace_core']:
        domain_match = 1.0

    # 2. Address Features
    digits_s1 = set(s1_feat['digits_enriched'])
    digits_t = set(target_feat['digits_enriched'])
    digit_jaccard = jaccard_similarity(digits_s1, digits_t)
    exact_digits_match = 1.0 if (digits_s1 and digits_s1 == digits_t) else 0.0
    has_shared_digit = 1.0 if (digits_s1 & digits_t) else 0.0

    loc_s1 = set(s1_feat['loc_tokens'])
    loc_t = set(target_feat['loc_tokens'])
    loc_jaccard = jaccard_similarity(loc_s1, loc_t)
    has_shared_loc = 1.0 if (loc_s1 & loc_t) else 0.0

    unit_s1 = set(s1_feat['units'])
    unit_t = set(target_feat['units'])
    unit_match = 1.0 if (unit_s1 and unit_s1 & unit_t) else 0.0

    state_match = 1.0 if (s1_feat['state'] and s1_feat['state'] == target_feat['state']) else 0.0

    # 3. Structural / Missingness Features
    s1_has_address = 1.0 if s1_feat['digits_enriched'] or s1_feat['loc_tokens'] else 0.0
    t_has_address = 1.0 if target_feat['digits_enriched'] or target_feat['loc_tokens'] else 0.0
    len_diff_core = float(abs(len(s1_feat['core']) - len(target_feat['core'])))
    
    # 4. New Advanced Features
    jw_name = jellyfish.jaro_winkler_similarity(s1_feat['core'], target_feat['core'])
    
    s1_t_len = len(s1_feat['tokens'])
    t_t_len = len(target_feat['tokens'])
    intersect_len = len(set(s1_feat['tokens']) & set(target_feat['tokens']))
    token_inclusion = intersect_len / min(s1_t_len, t_t_len) if min(s1_t_len, t_t_len) > 0 else 0.0
    
    s1_addr = " ".join(list(s1_feat['digits_enriched']) + list(s1_feat['loc_tokens']))
    t_addr = " ".join(list(target_feat['digits_enriched']) + list(target_feat['loc_tokens']))
    addr_lev = levenshtein_similarity(s1_addr, t_addr)
    
    s1_core_len = len(s1_feat['core'])
    t_core_len = len(target_feat['core'])
    length_ratio = min(s1_core_len, t_core_len) / max(s1_core_len, t_core_len) if max(s1_core_len, t_core_len) > 0 else 0.0

    return {
        'exact_core_match': exact_core_match,
        'token_jaccard': token_jaccard,
        'ngram_jaccard': ngram_jaccard,
        'levenshtein_name': lev_name,
        'prefix4_match': prefix4_match,
        'cons_tri_match': cons_tri_match,
        'collapsed_match': collapsed_match,
        'domain_match': domain_match,
        'digit_jaccard': digit_jaccard,
        'exact_digits_match': exact_digits_match,
        'has_shared_digit': has_shared_digit,
        'loc_jaccard': loc_jaccard,
        'has_shared_loc': has_shared_loc,
        'unit_match': unit_match,
        'state_match': state_match,
        's1_has_address': s1_has_address,
        't_has_address': t_has_address,
        'len_diff_core': len_diff_core,
        'jaro_winkler_name': jw_name,
        'token_inclusion_ratio': token_inclusion,
        'address_levenshtein': addr_lev,
        'length_ratio': length_ratio,
    }
