#!/usr/bin/env python3
"""
Candidate Partition Merger for Distributed Execution.

Merges the 4 candidate partition TSVs generated by team members into a single,
validated candidate_pairs.tsv conforming to the ML Challenge submission standard.

Usage:
  python -m blocking.merge_candidates \\
      --parts partitions/candidate_pairs_part0.tsv \\
              partitions/candidate_pairs_part1.tsv \\
              partitions/candidate_pairs_part2.tsv \\
              partitions/candidate_pairs_part3.tsv \\
      --order-reference student_resource/dataset/test/test_source1.tsv \\
      --output candidate_pairs.tsv
"""

import os
import sys
import argparse
from typing import List, Dict

EXPECTED_HEADER = ["source1_entity_id", "candidate_entity_ids"]

def merge_candidate_partitions(part_files: List[str], order_ref_path: str, output_path: str):
    print("\n=======================================================")
    print("MERGING CANDIDATE PARTITIONS")
    print("=======================================================")

    # 1. Read reference order if provided
    ref_order = []
    if order_ref_path and os.path.isfile(order_ref_path):
        print(f"Reading S1 entity sequence from reference: {order_ref_path}")
        with open(order_ref_path, 'r', encoding='utf-8') as f:
            next(f)
            for line in f:
                if line.strip():
                    ref_order.append(line.split('\t', 1)[0].strip())
        print(f"Reference S1 count: {len(ref_order):,}")

    # 2. Ingest candidate partitions
    merged_candidates: Dict[str, str] = {}
    total_parts_processed = 0

    for p in part_files:
        if not os.path.isfile(p):
            raise FileNotFoundError(f"Partition file not found: {p}")
        print(f"Reading partition: {p}")
        with open(p, 'r', encoding='utf-8') as f:
            header_line = f.readline()
            headers = [h.strip() for h in header_line.rstrip('\r\n').split('\t')]
            if headers != EXPECTED_HEADER:
                raise ValueError(f"Invalid header in {p}: {headers}. Expected: {EXPECTED_HEADER}")

            part_count = 0
            for line_no, line in enumerate(f, start=2):
                if not line.strip():
                    continue
                s1_id, tab, rest = line.partition('\t')
                s1_id = s1_id.strip()
                if not tab:
                    raise ValueError(f"Malformed row at line {line_no} in {p}: {line.rstrip()!r}")
                if s1_id in merged_candidates:
                    raise ValueError(f"Duplicate S1 ID detected across partitions: {s1_id}")
                merged_candidates[s1_id] = rest.rstrip('\r\n')
                part_count += 1

            print(f"  Loaded {part_count:,} queries from {p}")
            total_parts_processed += 1

    print(f"\nTotal merged unique queries: {len(merged_candidates):,}")

    # 3. Check reference alignment if available
    if ref_order:
        missing = set(ref_order) - set(merged_candidates.keys())
        extra = set(merged_candidates.keys()) - set(ref_order)
        if missing:
            raise ValueError(f"Missing {len(missing)} S1 queries from merged output! E.g.: {list(missing)[:5]}")
        if extra:
            raise ValueError(f"Found {len(extra)} unexpected S1 queries not in reference! E.g.: {list(extra)[:5]}")
        print("Reference verification: 100% S1 match with test_source1.tsv.")

    # 4. Write output file
    os.makedirs(os.path.dirname(os.path.abspath(output_path)) or '.', exist_ok=True)
    print(f"Writing merged candidates to: {output_path}...")
    with open(output_path, 'w', encoding='utf-8') as out_f:
        out_f.write("source1_entity_id\tcandidate_entity_ids\n")
        keys_to_write = ref_order if ref_order else list(merged_candidates.keys())
        for s1_id in keys_to_write:
            cands_str = merged_candidates.get(s1_id, "")
            out_f.write(f"{s1_id}\t{cands_str}\n")

    file_size_mb = os.path.getsize(output_path) / (1024 * 1024)
    print("-------------------------------------------------------")
    print(f"Merge Complete: {output_path} ({file_size_mb:.2f} MB)")
    print("=======================================================\n")
    return output_path

def main():
    parser = argparse.ArgumentParser(description="Merge 4 candidate partitions into candidate_pairs.tsv")
    parser.add_argument("--parts", nargs="+", required=True, help="List of candidate partition TSV files")
    parser.add_argument("--order-reference", default="student_resource/dataset/test/test_source1.tsv", help="Path to original S1 file for ordering")
    parser.add_argument("--output", default="candidate_pairs.tsv", help="Path to write merged candidate_pairs.tsv")
    args = parser.parse_args()

    merge_candidate_partitions(args.parts, args.order_reference, args.output)

if __name__ == "__main__":
    main()
